### ISSUE TITLE
codestyle

### ISSUE THREAD

**Issue by OleksandrLarin** [EvgenusT/ITEA_HomeWork#1]
переменный лучше обьявлять как можно ближе к месту испльзования
https://github.com/EvgenusT/ITEA_Lesson1_Task_1_3/blob/193d29fa3fc248022253ef1bf896dbe7e3adf58e/src/Lesson_1/Task_1.java#L18

**Comment by EvgenusT** [comment]
переместил данную строку максимально близко к месту использования
